webpackJsonp([0,2],{/***/
0:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}var r=t(1),o=n(r),a=t(28),u=t(166),i=n(u);t(174),(0,a.render)(o.default.createElement(i.default,null),document.getElementById("app"))},/***/
166:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(exports,"__esModule",{value:!0});var r=t(1),o=n(r),a=t(167),u=n(a),i=function(){return o.default.createElement("div",null,o.default.createElement(u.default,null))};exports.default=i},/***/
167:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}function r(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function o(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}function a(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)}Object.defineProperty(exports,"__esModule",{value:!0});var u=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=t(1),l=n(i),c=t(28),s=t(168),f=n(s),p=t(169),d=n(p),b=t(170),m=n(b),y=t(173),h=function(e){function t(e){r(this,t);var n=o(this,(t.__proto__||Object.getPrototypeOf(t)).call(this,e));return n.state={thumbs:[]},n.handleSnap=n.handleSnap.bind(n),n}return a(t,e),u(t,[{key:"componentDidMount",value:function(){var e={video:!0,audio:!1},t=(0,c.findDOMNode)(this.refs.video);navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia,navigator.getUserMedia(e,function(e){window.stream=e,window.URL?t.src=window.URL.createObjectURL(e):t.srcObject=e},function(e){alert(e)})}},{key:"handleSnap",value:function(){var e=(0,c.findDOMNode)(this.refs.video),t=(0,c.findDOMNode)(this.refs.drawmap);t.width=e.clientWidth,t.height=e.clientHeight,t.getContext("2d").drawImage(e,0,0,e.clientWidth,e.clientHeight);var n=t.toDataURL("image/jpeg"),r=(new Date).toGMTString(),o=(0,y.getTimeNum)(),a=10;this.setState(function(e){return e.thumbs.push({src:n,meta:{name:o,size:a,timestamp:r}})})}},{key:"render",value:function(){return l.default.createElement("div",{className:"camera-box"},l.default.createElement("video",{ref:"video",autoPlay:!0}),l.default.createElement("canvas",{id:"drawmap",ref:"drawmap"}),l.default.createElement(f.default,null,l.default.createElement(d.default,{onSnap:this.handleSnap})),l.default.createElement(m.default,{thumbs:this.state.thumbs}))}}]),t}(i.Component);exports.default=h},/***/
168:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(exports,"__esModule",{value:!0});var r=t(1),o=n(r),a=function(e){return o.default.createElement("div",{className:"buttons"},e.children)};exports.default=a},/***/
169:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}function r(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function o(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}function a(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)}Object.defineProperty(exports,"__esModule",{value:!0});var u=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=t(1),l=n(i),c=function(e){function t(e){return r(this,t),o(this,(t.__proto__||Object.getPrototypeOf(t)).call(this,e))}return a(t,e),u(t,[{key:"render",value:function(){return l.default.createElement("div",{className:"snapButton"},l.default.createElement("span",{className:"button",onClick:this.props.onSnap}))}}]),t}(i.Component);c.propTypes={onSnap:i.PropTypes.func.isRequire},exports.default=c},/***/
170:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}function r(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function o(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}function a(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)}Object.defineProperty(exports,"__esModule",{value:!0});var u=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=t(1),l=n(i),c=t(171),s=n(c),f=function(e){function t(e){return r(this,t),o(this,(t.__proto__||Object.getPrototypeOf(t)).call(this,e))}return a(t,e),u(t,[{key:"render",value:function(){var e=[].concat(this.props.thumbs).reverse();return l.default.createElement("ul",{className:"thumbbox"},e.map(function(e){return l.default.createElement("li",{key:Math.random()},l.default.createElement(s.default,{src:e.src,meta:e.meta}))}))}}]),t}(i.Component);f.propTypes={thumbs:i.PropTypes.array.isRequired},exports.default=f},/***/
171:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}function r(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function o(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}function a(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)}Object.defineProperty(exports,"__esModule",{value:!0});var u=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=t(1),l=n(i),c=(t(28),t(172)),s=n(c),f=function(e){function t(e){return r(this,t),o(this,(t.__proto__||Object.getPrototypeOf(t)).call(this,e))}return a(t,e),u(t,[{key:"render",value:function(){var e=this.props.src,t=this.props.meta,n=t.name,r=t.size,o=t.timestamp,a=e.substring(e.indexOf("/")+1,e.indexOf(";"));return"jpeg"===a&&(a="jpg"),l.default.createElement("div",{className:"thumb"},l.default.createElement("p",{className:"meta"},l.default.createElement("span",null,n),l.default.createElement("span",null,r),l.default.createElement("span",null,o)),l.default.createElement(s.default,{src:e,name:n,ext:a}),l.default.createElement("img",{ref:"img",src:e}))}}]),t}(i.Component);f.propTypes={src:i.PropTypes.string.isRequired,//dataURI
meta:i.PropTypes.shape({name:i.PropTypes.string.isRequired,size:i.PropTypes.number.isRequired,timestamp:i.PropTypes.string.isRequired})},exports.default=f},/***/
172:/***/
function(e,exports,t){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}function r(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function o(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}function a(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)}Object.defineProperty(exports,"__esModule",{value:!0});var u=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=t(1),l=n(i),c=function(e){function t(e){r(this,t);var n=o(this,(t.__proto__||Object.getPrototypeOf(t)).call(this,e));return n.onDownload=n.onDownload.bind(n),n}return a(t,e),u(t,[{key:"onDownload",value:function(){var e=this.props,t=e.src,n=e.name,r=e.ext,o=document.createElement("a");o.setAttribute("href",t),o.setAttribute("download",n+"."+r),o.style.display="none",document.body.appendChild(o),o.click(),document.body.removeChild(o)}},{key:"render",value:function(){return l.default.createElement("span",{className:"button thumb-button",onClick:this.onDownload},"Download")}}]),t}(i.Component);c.propTypes={src:i.PropTypes.string.isRequire,name:i.PropTypes.string,ext:i.PropTypes.string},c.defaultProps={name:"download",ext:"png"},exports.default=c},/***/
173:/***/
function(e,exports){"use strict";Object.defineProperty(exports,"__esModule",{value:!0});
//Add pre zero for number which is less than 10
var t=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:0;return e<10?"0"+e:""+e};exports.getTimeNum=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:new Date;return e.getFullYear()+""+t(e.getMonth()+1)+t(e.getDate())+t(e.getHours())+t(e.getMinutes())+t(e.getSeconds())+e.getMilliseconds()}},/***/
174:/***/
function(e,exports){}});